=== Tobi2001/asr_object_database/xsd/ConfigurationXMLSchema.xsd
<?xml version="1.0"  encoding="UTF-8" ?>
<xs:schema targetNamespace="http://xml.ralfschleicher.de/asr_object_database/" xmlns="http://xml.ralfschleicher.de/asr_object_database/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="database">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="uniqueName" type="xs:string" />
              <xs:element name="basenameMatchPattern" type="xs:string" />
              <xs:element name="objectDbRootFolder" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Tobi2001/asr_object_database/rsc/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://xml.ralfschleicher.de/asr_object_database/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.ralfschleicher.de/asr_object_database/ ../xsd/ConfigurationXMLSchema.xsd">
  <database>
    <uniqueName>textured</uniqueName>
    <basenameMatchPattern>.*</basenameMatchPattern>
    <objectDbRootFolder>package://asr_object_database/rsc/databases/textured_objects/</objectDbRootFolder>
  </database>
  <database>
    <uniqueName>segmentable</uniqueName>
    <basenameMatchPattern>.*</basenameMatchPattern>
    <objectDbRootFolder>package://asr_object_database/rsc/databases/segmentable_objects/</objectDbRootFolder>
  </database>
  <database>
    <uniqueName>descriptor</uniqueName>
    <basenameMatchPattern>.*</basenameMatchPattern>
    <objectDbRootFolder>package://asr_object_database/rsc/databases/descriptor_objects/</objectDbRootFolder>
  </database>
   <database>
    <uniqueName>marker</uniqueName>
    <basenameMatchPattern>.*</basenameMatchPattern>
    <objectDbRootFolder>package://asr_object_database/rsc/databases/marker/</objectDbRootFolder>
  </database>
</configuration>
